name: Process and Combine Videos with Dynamic Glitch Effect

# ワークフローを手動で実行できるようにするトリガー
on:
  workflow_dispatch:

jobs:
  build_video:
    # 最新のUbuntu環境で実行
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのコンテンツをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. FFmpegをインストール
      - name: Setup FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # 3. 動画処理を実行（エラー修正版）
      - name: Process videos with FFmpeg
        run: |
          ffmpeg -i video2.mp4 -i video1.mp4 -filter_complex \
          "[1:v]format=rgba, \
          geq=r=r(X\\,Y):g=g(X\\,Y):b=b(X\\,Y):a='if( \
          lt( \
            sqrt( \
              pow(r(X\\,Y)-(128+127*sin(2*PI*t/10))\\,2) + \
              pow(g(X\\,Y)-(128+127*sin(2*PI*t/10+2*PI/3))\\,2) + \
              pow(b(X\\,Y)-(128+127*sin(2*PI*t/10+4*PI/3))\\,2) \
            )\\, 60 \
          )\\, 0\\, 255 \
          )'[fg]; \
          [0:v][fg]overlay[merged]; \
          [merged]tblend=all_mode=difference,framerate=15,format=yuv420p" \
          -c:a copy output.mp4
          
      # 4. 処理した動画をリポジトリにプッシュ
      - name: Commit and push processed video
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output.mp4
          # ファイルに変更があった場合のみコミットとプッシュを実行
          git diff --staged --quiet || (git commit -m "✨ Add dynamic glitched video" && git push)
