name: Process and Combine Videos with Dynamic Glitch Effect

on:
  workflow_dispatch:

jobs:
  build_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Create filter_complex script
        run: |
          cat <<'EOF' > filter_script.txt
          [1:v]format=rgba,geq=r='r(X,Y)':g='g(X,Y)':b='b(X,Y)':a='if(lt(sqrt(pow(r(X,Y)-128,2)+pow(g(X,Y)-128,2)+pow(b(X,Y)-128,2)),60),0,255)'[fg];
          [0:v][fg]overlay[merged];
          [merged]tblend=all_mode=difference,framerate=15,format=yuv420p
          EOF


      - name: Process videos with FFmpeg using script
        run: |
          ffmpeg -y -i video2.mp4 -i video1.mp4 -filter_complex_script filter_script.txt -c:v libx264 -preset veryfast -crf 23 -c:a copy output.mp4

      - name: Commit and push processed video
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output.mp4
          git diff --staged --quiet || (git commit -m "✨ Add dynamic glitched video" && git push)
