name: Video Processing & Upload Workflow

on:
  workflow_dispatch:

env:
  FINAL_VIDEO_NAME: 'final_video.mp4'

jobs:
  process_and_upload:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install system packages (ffmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python-headless numpy

      - name: Show inputs
        run: |
          echo "Listing working directory"
          ls -la

      - name: Run video processing script
        run: |
          python random_chroma.py

      - name: Show result info
        run: |
          if [ -f "${{ env.FINAL_VIDEO_NAME }}" ]; then
            echo "Output file:"
            ls -lh "${{ env.FINAL_VIDEO_NAME }}"
            md5sum "${{ env.FINAL_VIDEO_NAME }}" || true
          else
            echo "No output file found"
            exit 1
          fi

      - name: Commit and push final video
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase || true
          git add ${{ env.FINAL_VIDEO_NAME }} || true
          git commit -m "Add/Update final video (workflow run ${{ github.run_id }})" || echo "No changes to commit"
          git push || echo "Push failed"

      - name: Upload final video as artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-video
          path: ${{ env.FINAL_VIDEO_NAME }}
