name: Video Processing & Upload Workflow

on:
  workflow_dispatch:
    # 手動実行時の入力項目
    inputs:
      tolerance:
        description: 'Chroma Key Tolerance (0-255)'
        required: true
        default: '50'
        type: string
      afterimage_strength:
        description: 'Afterimage Strength (0.0 to 1.0)'
        required: true
        default: '0.3'
        type: string
      overlay_color:
        description: 'Overlay Color (hex, e.g., #FF5733 or none)'
        required: true
        default: 'none'
        type: string
      overlay_strength:
        description: 'Overlay Strength (0.0 to 1.0)'
        required: true
        default: '0.4'
        type: string

env:
  MP4_VIDEO_NAME: 'final_video.mp4'
  FINAL_VIDEO_NAME: 'final_video.mov'

jobs:
  process_and_upload:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Python 3.x 環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. 必要なライブラリをインストール
      - name: Install Python dependencies
        run: |
          pip install opencv-python numpy

      # 4. 入力値を使ってPythonスクリプトを実行
      - name: Run video processing script
        run: |
          python random_chroma.py \
            --tolerance ${{ github.event.inputs.tolerance }} \
            --afterimage-strength ${{ github.event.inputs.afterimage_strength }} \
            --overlay-color "${{ github.event.inputs.overlay_color }}" \
            --overlay-strength ${{ github.event.inputs.overlay_strength }}

      # 5. ffmpegをインストール
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # 6. ffmpegを使ってMP4をMOVに変換
      - name: Convert MP4 to MOV
        run: |
          ffmpeg -i ${{ env.MP4_VIDEO_NAME }} ${{ env.FINAL_VIDEO_NAME }}

      # 7. 完成した動画 (MOV) を main ブランチにコミット & プッシュ
      - name: Commit and push final video
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add ${{ env.FINAL_VIDEO_NAME }}
          git commit -m "Add/Update final video as MOV (workflow run ${{ github.run_id }})" || echo "No changes to commit"
          git push

      # 8. (オプション) アーティファクトとしてもアップロード
      - name: Upload final video as artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-video
          path: ${{ env.FINAL_VIDEO_NAME }}
