name: Process and Composite Videos

on:
  workflow_dispatch:
    inputs:
      base_video:
        description: '基準にする動画ファイル名 (この動画の長さに合わせる)'
        required: true
        default: 'video1.mp4'
      overlay_video:
        description: '重ねる動画ファイル名 (速度が変更される)'
        required: true
        default: 'video2.mp4'
      output_file:
        description: '出力する動画ファイル名'
        required: true
        default: 'processed_video.mp4'

jobs:
  process:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          pip install opencv-python-headless numpy
      
      # ★★★ 修正箇所: 4番目の引数(色の指定)を削除 ★★★
      - name: Run video processing script
        run: |
          python process_videos.py "${{ github.event.inputs.base_video }}" "${{ github.event.inputs.overlay_video }}" "${{ github.event.inputs.output_file }}"

      - name: Commit and push processed video
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add "${{ github.event.inputs.output_file }}"
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "feat: Add processed video ${{ github.event.inputs.output_file }}" -m "[skip ci]"
            git push
          fi
